CREATE USER manager IDENTIFIED BY admin;
GRANT CONNECT TO manager;
GRANT CREATE SESSION TO manager;
GRANT CONNECT, RESOURCE, DBA TO manager;
GRANT UNLIMITED TABLESPACE TO manager;
GRANT CREATE SESSION TO manager;
COMMIT;